name: Terraform EC2 Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      aws_region:
        description: "Choose AWS region"
        required: true
        default: "eu-west-2"
        type: choice
        options:
          - eu-west-2
          - us-east-1
          - ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.event.inputs.aws_region }}
      ACTION: ${{ github.event.inputs.action }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply/Destroy
        run: |
          if [ "${ACTION}" = "apply" ]; then
            terraform apply -auto-approve -var="aws_region=${AWS_REGION}"
          else
            terraform destroy -auto-approve -var="aws_region=${AWS_REGION}"
          fi

      - name: Get EC2 Public IP
        if: ${{ github.event.inputs.action == 'apply' }}
        id: ec2ip
        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_ENV
          echo "EC2 Public IP: $EC2_IP"

      - name: Install Apache if not installed
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ env.ec2_ip }} << 'EOF'
          if ! dpkg -l | grep apache2; then
            sudo apt-get update -y
            sudo apt-get install -y apache2
            sudo systemctl enable apache2
            sudo systemctl start apache2
          else
            echo "Apache already installed"
          fi
          EOF
